# Generated by Django 2.2 on 2021-03-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_socio_grpc', '0003_grcperrorcode_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcperrorcode',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
